<?php

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * $features_list
 *
 * On peut ajouter/supprimer
 * NE JAMAIS CHANGER LE NOM DES CLÉS
 * Ne JAMAIS SUPPRIMER et AJOUTER UNE CLÉ DANS LA MÊME VERSION
 */
$features_list = array(
	'all-features-advanced' => array(
		'active'         => true,
		'title'          => esc_html__( 'Tous les composants activés', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => '',
		'help_url_class' => '',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
	),
	'acf-dynamic-tag'       => array(
		'active'         => true,
		'title'          => esc_html__( 'ACF balises dynamiques', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/how-to-integrate-and-use-acf-fields-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ACF_INCLUDES . 'dynamic-tags/eac-acf-tags.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'acf-image-gallery'     => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF galerie d&#039;images', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups', 'acf_register_field_type' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/add-and-publish-an-image-gallery-with-the-free-version-of-acf/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ACF_INCLUDES . 'gallery/class-eac-acf-field-gallery.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'acf-json'              => array(
		'active'         => false,
		'title'          => 'ACF JSON',
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => '#',
		'help_url_class' => 'eac-admin-help acf-json',
		'file_path'      => EAC_ACF_INCLUDES . 'eac-acf-json.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'acf-option-page'       => array(
		'active'         => false,
		'title'          => esc_html__( 'ACF page d&#039;options', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => 'https://elementor-addon-components.com/add-options-page-for-the-free-version-of-acf/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ACF_INCLUDES . 'eac-acf-options-page.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'alt-attribute'         => array(
		'active'         => false,
		'title'          => esc_html__( 'ALT attribut', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/add-external-image-for-elementor/#improve-your-seo-with-the-dynamic-tag-external-image',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'injection/eac-injection-image.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'custom-attribute'      => array(
		'active'         => false,
		'title'          => esc_html__( 'Attributs personnalisés', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/add-your-custom-attributes-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'custom-attributes/eac-custom-attributes.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'custom-css'            => array(
		'active'         => true,
		'title'          => esc_html__( 'CSS personnalisé', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/elementor-custom-css/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'custom-css/eac-custom-css.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'dynamic-tag'           => array(
		'active'         => true,
		'title'          => esc_html__( 'Balises dynamiques', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/elementor-dynamic-tags/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'dynamic-tags/eac-dynamic-tags.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'dysplay-condition'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Conditions d&#039;affichage', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/how-to-set-display-conditions-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_CONDITION_PATH . 'module.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'element-link'          => array(
		'active'         => false,
		'title'          => esc_html__( 'Lien élément', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/add-link-to-a-section-column-using-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'injection/eac-injection-links.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'lottie-background'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Lottie d&#039;arrière-plan', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/add-lottie-animation-in-elementor/#use-lottie-animations-in-the-background-of-an-element',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'injection/eac-injection-lottie.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'kenburns-slideshow'    => array(
		'active'         => false,
		'title'          => esc_html__( 'Effet Ken Burns', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/animation-dimages/#ken-burns-slideshow-for-background-images',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'injection/eac-injection-kenburns.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'motion-effects'        => array(
		'active'         => false,
		'title'          => esc_html__( 'Effets de mouvement', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/create-animation-effects-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'injection/eac-injection-effect.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'background-images'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Multiples images de fond', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/add-multiple-background-images-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'injection/eac-injection-background-images.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'element-sticky'        => array(
		'active'         => false,
		'title'          => esc_html__( 'Sticky élément', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://elementor-addon-components.com/use-sticky-scrolling-effect-with-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_ELEMENTOR_INCLUDES . 'injection/eac-injection-sticky.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'woo-dynamic-tag'       => array(
		'active'         => false,
		'title'          => esc_html__( 'WC balises dynamiques', 'eac-components' ),
		'class_depends'  => array( 'WooCommerce' ),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => 'https://elementor-addon-components.com/dynamic-woocommerce-tags-for-elementor/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_WC_INCLUDES . 'dynamic-tags/eac-woo-tags.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'all-features-common'   => array(
		'active'         => false,
		'title'          => esc_html__( 'Tous les composants activés', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => '',
		'help_url_class' => '',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
	),
	'custom-nav-menu'       => array(
		'active'         => false,
		'title'          => esc_html__( 'Personnaliser le menu de navigation', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/customize-wordpress-navigation-menus/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => EAC_PLUGIN_PATH . 'admin/settings/eac-nav-menu.php',
		'name_space'     => '',
		'badge'          => '',
	),
	'grant-option-page'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Accès page d&#039;options', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array( 'acf_get_field_groups' ),
		'elems_exclude'  => array( 'acf_register_block_type' ),
		'help_url'       => '#',
		'help_url_class' => 'eac-admin-help grant-option-page',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
	),
	'unfiltered-medias'     => array(
		'active'         => false,
		'title'          => esc_html__( 'Téléverser les fichiers non filtrés', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => '#',
		'help_url_class' => 'eac-admin-help grant-medias-upload',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
	),
	'extend-fields-medias'  => array(
		'active'         => false,
		'title'          => esc_html__( 'Médias champs personnalisés', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'help_url'       => 'https://elementor-addon-components.com/create-advanced-image-gallery-using-elementor/#activate-a-link-and-add-keywords-to-the-filter',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
	),
	'preload-page'  => array(
		'active'         => false,
		'title'          => esc_html__( 'Préchargement des pages', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array( 'ELEMENTOR_PRO_VERSION' ),
		'help_url'       => 'https://instant.page/',
		'help_url_class' => 'eac-admin-help',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
	),
	'widget-count'  => array(
		'active'         => false,
		'title'          => esc_html__( 'Utilisation des éléments', 'eac-components' ),
		'class_depends'  => array(),
		'func_depends'   => array(),
		'elems_exclude'  => array(),
		'help_url'       => '#',
		'help_url_class' => 'eac-admin-help grant-elements-usage',
		'file_path'      => '',
		'name_space'     => '',
		'badge'          => '',
	),
);

return $features_list;
